name: CD TEST
on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  checking-and-deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Staging Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/test/cicd_testing
            git pull origin master
            ls -all
            echo "Deployed Successfully"