name: CI TEST
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checking-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        run: |
          echo "Checking Dependencies Complete"
          echo "Checking Data Complete"
          echo "All Complete..."
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploying to Server
        run: |
          echo "Deploy Complete."